CREATE TABLE IF NOT EXISTS member (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    password VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS board (
    no INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id VARCHAR(50) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(500) NOT NULL
);